# Generated by Django 2.0.4 on 2018-04-23 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Directory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('dir_id', models.CharField(max_length=50)),
                ('url', models.URLField(max_length=300)),
            ],
        ),
    ]
