# Generated by Django 2.0.4 on 2018-04-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail_script', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directory',
            options={'verbose_name_plural': 'Directories'},
        ),
        migrations.AddField(
            model_name='directory',
            name='emails_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='directory',
            name='urls_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
