# Generated by Django 2.0.4 on 2018-04-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail_script', '0003_auto_20180424_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directory',
            name='url',
        ),
    ]
